package com.spendsmart.recurring.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "recurring_schedules")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RecurringSchedule {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "User email is required")
    private String userEmail; // from JWT

    @NotNull(message = "Recurring rule ID is required")
    private Long recurringRuleId;

    @NotBlank(message = "Task name is required")
    private String taskName;

    @NotBlank(message = "Task type is required")
    private String taskType; // BUDGET_CREATION, EXPENSE_CREATION, PAYMENT_REMINDER

    @NotNull(message = "Scheduled date is required")
    private String scheduledDate;

    @NotNull(message = "Scheduled time is required")
    private String scheduledTime;

    private String status; // PENDING, COMPLETED, FAILED, CANCELLED

    private String executionResult; // Result of the execution

    private String errorMessage; // Error message if failed

    private Integer retryCount; // Number of retry attempts

    private String lastExecutionDate; // When it was last executed

    private String nextRetryDate; // When to retry if failed

    private Boolean isAutoGenerated; // Whether this was auto-generated

    private String metadata; // JSON string for additional data
}
